SELECT CART_ID 
FROM CART_PRODUCTS
WHERE (CART_ID, 'Milk') IN (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk' OR NAME = 'Yogurt'
    GROUP BY CART_ID
) AND (CART_ID, 'Yogurt') IN (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk' OR NAME = 'Yogurt'
    GROUP BY CART_ID
)
GROUP BY CART_ID;