SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID NOT IN (
    SELECT DISTINCT T1.ITEM_ID
    FROM ITEM_TREE T1
    INNER JOIN ITEM_TREE T2 ON T1.ITEM_ID = T2.PARENT_ITEM_ID
)
ORDER BY I.ITEM_ID DESC;
