SELECT ID, 
CASE
    WHEN T2.CHILD_COUNT IS NOT NULL
    THEN T2.CHILD_COUNT
    ELSE 0
END CHILD_COUNT
FROM ECOLI_DATA T1
LEFT OUTER JOIN (SELECT PARENT_ID, COUNT(*) CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
     ) T2 ON T1.ID = T2.PARENT_ID;