SELECT E.ID, CASE
    WHEN E.PERCENT <= 25 THEN 'CRITICAL'
    WHEN E.PERCENT <= 50 THEN 'HIGH'
    WHEN E.PERCENT <= 75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 AS PERCENT
    FROM ECOLI_DATA
) AS E 
ORDER BY ID;