WITH RECURSIVE cte AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n + 1 FROM cte WHERE n < 23
)

SELECT n AS HOUR, IFNULL(COUNT(A.ANIMAL_ID), 0) AS COUNT
FROM cte
LEFT JOIN ANIMAL_OUTS A ON cte.n = HOUR(A.DATETIME)
GROUP BY n
ORDER BY n;