SELECT B.WRITER_ID USER_ID, U.NICKNAME NICKNAME, SUM(B.PRICE) TOTAL_SALES 
FROM USED_GOODS_BOARD B 
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000
ORDER BY 3;
